name: super-action
on: [push, pull_request]
jobs:
  steve-job:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
        name: "Print current directory"

      - run: echo "Hello, World. I'm Steve Jobs"